"""Prometheus metrics exposed at GET /metrics."""

from prometheus_client import Counter, Gauge, Histogram

_BUCKETS = (0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 4, 8, 16, 32)

REQUEST_LATENCY = Histogram("llmrag_request_seconds", "End-to-end request latency", ["endpoint", "cached"],
                            buckets=_BUCKETS)
STAGE_LATENCY = Histogram("llmrag_stage_seconds", "Latency of pipeline stages", ["stage"], buckets=_BUCKETS)
TTFT = Histogram("llmrag_time_to_first_token_seconds", "Streaming time to first token", buckets=_BUCKETS)
CACHE_EVENTS = Counter("llmrag_cache_events_total", "Response cache hits and misses", ["result"])
TOKENS_GENERATED = Counter("llmrag_generated_tokens_total", "Tokens generated by the LLM")
CHUNKS_INDEXED = Gauge("llmrag_chunks_indexed", "Number of chunks in the retrieval index")
